[platformio]
default_envs = xiao_esp32c6

[env:xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -D CORE_DEBUG_LEVEL=0
