#pragma once
// ARGUS theme.
//
// The 13-37 base hardcoded its matrix-green accent as lv_color_make(0x00,0xCC,0x66)
// (and a brighter "active" lv_color_make(0x00,0xFF,0x80)) at ~67 sites across the
// screens. This header centralizes the ARGUS brand palette so the accent lives
// in one place: calm steel-blue at rest, HADES threat-red for the alert state
// (brand-as-functional-state). Colors are lv_color_make(r,g,b); LVGL converts to
// the panel's native format.
#include <lvgl.h>

// Brand accent, at rest (calm) — ARGUS steel-blue (#9BBCD6).
// Drop-in replacement for the old matrix-green lv_color_make(0x00,0xCC,0x66).
#define ARGUS_ACCENT         lv_color_make(0x9B, 0xBC, 0xD6)

// Brighter "active / live" accent — drop-in for lv_color_make(0x00,0xFF,0x80).
#define ARGUS_ACCENT_ACTIVE  lv_color_make(0xC8, 0xDE, 0xF0)

// Dim accent for idle / secondary structure.
#define ARGUS_ACCENT_DIM     lv_color_make(0x5B, 0x7C, 0x96)

// Secondary body/label TEXT colour. The maintainer preferred the secondary text in a
// warm white/cream over the steel-blue accent, so these carry body text while the
// accent is reserved for structure/titles. ARGUS_TEXT = bright cream, _DIM = a
// softer warm grey for captions/hints.
#define ARGUS_TEXT           lv_color_make(0xED, 0xE8, 0xDA)
#define ARGUS_TEXT_DIM       lv_color_make(0xB2, 0xAB, 0x98)

// HADES threat-red (#DB615A) — the "red eyes" alert state.
#define HADES_RED            lv_color_make(0xDB, 0x61, 0x5A)

// Offense-mode base accent — amber "teeth" (#F0A030). Distinct from the calm
// steel-blue (Daily/Defense) and from HADES_RED (which still overlays as the
// threat/alert state on top of this). Drives the Offense border + "OFF" chip.
#define ARGUS_OFFENSE_ACCENT lv_color_make(0xF0, 0xA0, 0x30)

// Runtime, state-aware accent. Returns ARGUS_ACCENT (steel-blue) at rest and
// HADES_RED when Threat Radar is flagging a tail (top level >= TR_LVL_LIKELY).
// High-visibility, frequently-repainted surfaces (clock status bar, Threat
// Radar screen) call this so the brand flips to the alert state live; static
// low-traffic screens keep using the ARGUS_ACCENT macro. Defined in theme.cpp.
lv_color_t argus_accent(void);

// Mode-aware BASE accent (no threat overlay): steel-blue in Daily/Defense, amber
// in Offense. argus_accent() layers the threat-red flip on top of this (except in
// Daily, which stays innocent and never flips). Defined in theme.cpp.
lv_color_t argus_base_accent(void);

// Persistent per-mode indicator on lv_layer_top(): hidden in Daily, a steel "DEF"
// chip in Defense, an amber/red border frame + "OFF" chip in Offense. init() once
// at boot (after LVGL/clock build); refresh() on every mode change and on the 1s
// status tick so the border/chip flip live under threat. Defined in theme.cpp.
void argus_mode_indicator_init(void);
void argus_mode_indicator_refresh(void);

// Pipeline-driven threat override for the brand accent. The detect_pipeline
// (WiFi evil-twin + beacon-flood aggregator, src/detect_pipeline.*) calls this
// to flip argus_accent() to HADES_RED when its ThreatState posture reaches
// Alert or above, independently of the GPS-co-movement Threat Radar. Passing
// false clears the override, so the accent falls back to the Threat Radar state.
// Default (never called) is false, so existing behavior is unchanged until the
// pipeline drives it. Defined in theme.cpp.
void argus_set_threat(bool active);

// Full-alphabet Bank Gothic brand font for screen titles (src/font_argus_ui.c).
LV_FONT_DECLARE(font_argus_ui);

// ARGUS UI text fonts (brand system): Orbitron for labels, VT323 for numeric/
// terminal readouts. Bank Gothic (font_argus_ui / the clock font) stays for the
// wordmark, titles, and the clock. Generated by tools/gen_clock_font.py from the
// OFL Orbitron / VT323 TTFs in tools/brandfonts/.
LV_FONT_DECLARE(font_argus_label_14);   // Orbitron 14 - small labels
LV_FONT_DECLARE(font_argus_label_16);   // Orbitron 16 - body labels
LV_FONT_DECLARE(font_argus_label_20);   // Orbitron 20 - tile labels, date
LV_FONT_DECLARE(font_argus_label_28);   // Orbitron 28 - larger labels
LV_FONT_DECLARE(font_argus_mono_16);    // VT323 16 - small numeric readouts
LV_FONT_DECLARE(font_argus_mono_48);    // VT323 48 subset (digits/colon) - big readouts (alarm/stopwatch/timer)
LV_FONT_DECLARE(font_argus_label_48);   // Orbitron 48 subset (START/STOP) - wardriver button
